#!/bin/bash

# skip pull requests by renovate bot
if [[ $TRAVIS_PULL_REQUEST_BRANCH = renovate/* ]]; then exit 0; fi

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

DOCKER_IMAGE=$TRAVIS_REPO_SLUG
DOCKER_DEV_TAG=$([ "$TRAVIS_BRANCH" == "master" ] || echo "-dev")
DOCKER_TAG=${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT:0:8}${DOCKER_DEV_TAG}
DOCKER_LATEST_TAG=latest${DOCKER_DEV_TAG}

echo "DOCKER_IMAGE: $DOCKER_IMAGE"
echo "DOCKER_TAG: $DOCKER_TAG"
echo "DOCKER_LATEST_TAG: $DOCKER_LATEST_TAG"
echo "SENTRY_AUTH_TOKEN: $SENTRY_AUTH_TOKEN"
echo "SENTRY_ORG: $SENTRY_ORG"
echo "SENTRY_PROJECT: $SENTRY_PROJECT"
echo "TRAVIS_COMMIT: $TRAVIS_COMMIT"

docker build \
  --build-arg GITHUB_AUTH_TOKEN=$GITHUB_AUTH_TOKEN \
  --build-arg SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN \
  --build-arg SENTRY_ORG=$SENTRY_ORG \
  --build-arg SENTRY_PROJECT=$SENTRY_PROJECT \
  --build-arg TRAVIS_COMMIT=$TRAVIS_COMMIT \
  -t $DOCKER_IMAGE:$DOCKER_LATEST_TAG . && \
docker tag $DOCKER_IMAGE:$DOCKER_LATEST_TAG $DOCKER_IMAGE:$DOCKER_TAG && \
docker push $DOCKER_IMAGE
