#!/bin/bash

DOCKER_IMAGE=$TRAVIS_REPO_SLUG
DOCKER_DEV_TAG=$([ "$TRAVIS_BRANCH" == "master" ] || echo "-dev")
DOCKER_TAG=${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT:0:8}${DOCKER_DEV_TAG}
DOCKER_LATEST_TAG=latest${DOCKER_DEV_TAG}

AUTHOR="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
COMMIT_HASH=${TRAVIS_COMMIT:0:8}
BUILD_URL=https://travis-ci.com/${TRAVIS_REPO_SLUG}/builds/${TRAVIS_BUILD_ID}
COMPARE_URL=https://github.com/${TRAVIS_REPO_SLUG}/compare/${TRAVIS_COMMIT_RANGE}

echo "Build <${BUILD_URL}|#${TRAVIS_BUILD_ID}> (<${COMPARE_URL}|${COMMIT_HASH}>) of <b>${TRAVIS_REPO_SLUG}@${TRAVIS_BRANCH}</b> by ${AUTHOR}"
echo "Commit message: ${TRAVIS_COMMIT_MESSAGE}"
